### ISSUE TITLE
php 8.2 cache rebuild errors

### ISSUE THREAD

**Issue by Cx-Developments** [mybb/mybb#4731]
I believe the root cause is line 640 in class_datacache.php located in the INC folder

`$usergroups = array_keys($this->read("usergroups", true)); // not returning an array key`

Error is as such:

`PHP Fatal error:  Uncaught TypeError: array_keys(): Argument #1 ($array) must be of type array, bool given in /home/[Hidden User]/[Hidden Directory]/inc/class_datacache.php:640
Stack trace:
#0 /home/[Hidden User]/[Hidden Directory]/inc/class_datacache.php(640): array_keys(false)
#1 /home/[Hidden User]/[Hidden Directory]/inc/class_datacache.php(625): datacache->build_forum_permissions()
#2 /home/[Hidden User]/[Hidden Directory]/admin/inc/functions.php(338): datacache->update_forumpermissions()
#3 /home/[Hidden User]/[Hidden Directory]/admin/modules/forum/management.php(1532): save_quick_perms(60)
#4 /home/[Hidden User]/[Hidden Directory]/admin/index.php(833): require('/home/dh_u7aey5...')
#5 {main}
  thrown in /home/[Hidden User]/[Hidden Directory]/inc/class_datacache.php on line 640
PHP Fatal error:  Uncaught TypeError: array_keys(): Argument #1 ($array) must be of type array, bool given in /home/[Hidden User]/[Hidden Directory]/inc/class_datacache.php:640
Stack trace:
#0 /home/[Hidden User]/[Hidden Directory]/inc/class_datacache.php(640): array_keys(false)
#1 /home/[Hidden User]/[Hidden Directory]/inc/class_datacache.php(625): datacache->build_forum_permissions()
#2 /home/[Hidden User]/[Hidden Directory]/admin/modules/forum/management.php(2086): datacache->update_forumpermissions()
#3 /home/[Hidden User]/[Hidden Directory]/admin/index.php(833): require('[Hidden Directory]...')
#4 {main}
  thrown in /home/[Hidden User]/[Hidden Directory]/inc/class_datacache.php on line 640`
  
  Using php 8.2 a resolution to this would be good because I am unable to modify my threads or add new ones

**Comment by effone** [comment]
Can't reproduce :((

**Comment by Sama34** [comment]
`array_keys()` expects an array, but `$this->read()` returns mixed (array|false).

The warning or error is expected.

A temporal solution would be to cast, like so :
`$usergroups = array_keys((array)$this->read("usergroups", true));`
